carcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cars/', views.cars_index, name='index'),
    path('cars/<int:car_id>/', views.cars_detail, name='detail'),
    path('cars/create/', views.CarCreate.as_view(), name='cars_create'),
    path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='cars_update'),
    path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='cars_delete'),
    path('cars/<int:car_id>/add_maintenance/', views.add_maintenance, name='add_maintenance'),
    path('cars/<int:car_id>/assoc_part/<int:part_id>/', views.assoc_part, name='assoc_part'),
    path('parts/', views.PartList.as_view(), name='parts_index'),
    path('parts/<int:pk>/', views.PartDetail.as_view(), name='parts_detail'),
    path('parts/create/', views.PartCreate.as_view(), name='parts_create'),
    path('parts/<int:pk>/update/', views.PartUpdate.as_view(), name='parts_update'),
    path('parts/<int:pk>/delete/', views.PartDelete.as_view(), name='parts_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
WORKS = (
    ('O', 'Oil Changed'),
    ('T', 'Tune Up'),
    ('R', 'Tire Rotation'),
)

class Part(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("parts_detail", kwargs={"pk": self.id})
    

class Car(models.Model):
    year = models.CharField(max_length=4)
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    comment = models.TextField(max_length=200)
    parts = models.ManyToManyField(Part)

    def __str__(self):
        return self.model

    def get_absolute_url(self):
        return reverse("detail", kwargs={'car_id': self.id})

class Maintenance(models.Model):
    date = models.DateField('maintenance date')
    work_done = models.CharField(
        max_length=1,
        choices=WORKS,
        default=[0][0]
    )

    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_work_done_display()} on {self.date}"

    class Meta:
        ordering = ['-date']
    

main_app/forms.py
from django.forms import ModelForm
from .models import Maintenance

class MaintenanceForm(ModelForm):
  class Meta:
    model = Maintenance
    fields = ['date', 'work_done']

main_app/views.py
from django.shortcuts import redirect, render
from .models import Car, Part
from .forms import MaintenanceForm

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

# CBV(Class Based View) functions

class CarCreate(CreateView):
    model = Car
    fields = ['year', 'make', 'model', 'comment']

class CarUpdate(UpdateView):
    model = Car
    fields = '__all__'

class CarDelete(DeleteView):
    model = Car
    success_url = '/cars/'

# Create your views here.
def add_maintenance(request, car_id):
    form = MaintenanceForm(request.POST)

    if form.is_valid():
        new_maintenance = form.save(commit=False)
        new_maintenance.car_id = car_id
        new_maintenance.save()
    return redirect('detail', car_id=car_id)

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cars_index(request):
    cars = Car.objects.all()
    return render(request, 'cars/index.html', { 'cars': cars })

def cars_detail(request, car_id):
    car = Car.objects.get(id=car_id)
    parts_car_doesnt_have = Part.objects.exclude(id__in = car.parts.all().values_list('id'))
    maintenance_form = MaintenanceForm()
    return render(request, 'cars/detail.html', { 
        'car': car,
        'maintenance_form': maintenance_form, 
        'parts': parts_car_doesnt_have
        })

def assoc_part(request, car_id, part_id):
    Car.objects.get(id=car_id).parts.add(part_id)
    return redirect('detail', car_id=car_id)

class PartList(ListView):
    model = Part

class PartDetail(DetailView):
    model = Part

class PartCreate(CreateView):
    model = Part
    fields = '__all__'

class PartUpdate(UpdateView):
    model = Part
    fields = ['name', 'type']

class PartDelete(DeleteView):
    model = Part
    success_url = '/parts/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Car Collector</h1>
<hr />
<p>Collect Some Cars!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Car Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper orange lighten-2">
        <ul>
          <li><a href="/" class="brand-logo right"><span class="red-text"><b>&nbsp;&nbsp;Car Collector</b></span></a></li>
        </ul>
        <ul class="left">
          <li><a href="{% url 'about' %}"><span class="red-text"><b>About</b></span></a></li>
          <li><a href="{% url 'parts_create' %}"><span class="red-text"><b>Add Car Part</b></span></a></li>
          <li><a href="{% url 'parts_index' %}"><span class="red-text"><b>View All Car Parts</b></span></a></li>
          <li><a href="{% url 'cars_create' %}"><span class="red-text"><b>Add Car</b></span></a></li>
          <li><a href="{% url 'index' %}"><span class="red-text"><b>View All My Cars</b></span></a></li>  
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer orange lighten-2">
    <div class="right"><span class="red-text"><b>All Rights Reserved, &copy; 2021 Car Collector &nbsp;</b></span></div>
  </footer>
</body>
</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Car Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title red-text"><b>{{ car.make }} {{ car.model }}</b></span>
        <p><b>Year:</b> {{ car.year }}</p>
        <p><b>Comments:</b> {{ car.comment }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cars_update' car.id %}" class="red-text">Edit</a>
        <a href="{% url 'cars_delete' car.id %}" class="red-text">Delete</a>
      </div>
  </div>
</div>
<div class="col s6">
 
    <form action="{% url 'add_maintenance' car.id %}" method='POST'>
	    {% csrf_token %}
	    {{ maintenance_form.as_p }}
	    <input type="submit" class='btn red black-text' value='Add Maintenance'>
    </form>


    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Work Done</th></tr>
      </thead>
      <tbody>
        {% for maintenance in car.maintenance_set.all %}
          <tr>
            <td>{{maintenance.date}}</td>
            <td>{{maintenance.get_work_done_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>Parts for {{ car.make }} {{ car.model }}</h3>
    {% if car.parts.count %}
      {% for part in car.parts.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span style="color: red"><b>{{ part.name }}</b></span><br><small><b>{{ part.type }}</b></small> 
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Parts Added</h5>
    {% endif %}
  </div>
</div>
<div class="col s6">
  <h3>Available Parts</h3>
  {% if parts.count %}
    {% for part in parts.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            <span class="red-text"><b>{{ part.name }}</b></span><br><small><b>{{ part.type }}</b></small>
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_part' car.id part.id %}" method="POST">
          {% csrf_token %}
          <button type="Submit" class="btn red black-text">Add</button>
          </form>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h5>{{ car.make }} {{ car.model }} Already Has All Parts Available</h5>
  {% endif %}
</div>
<script>
      const dateEl = document.getElementById('id_date');
      M.Datepicker.init(dateEl, {
              format: 'yyyy-mm-dd',
              defaultDate: new Date(),
              setDefaultDate: true,
              autoClose: true
      });
      const selectEl = document.getElementById('id_work_done');
      M.FormSelect.init(selectEl)
</script>

{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Car List</h1>

{% for car in cars %}
  <div class="card">
    <a href="/cars/{{ car.id }}" class="black-text">
    <div class="card-content">
      <span class="card-title red-text"><b>{{ car.make }} {{ car.model }}</b></span>
      <p><b>Year:</b> {{ car.year }}</p>
      <p><b>Comments:</b> {{ car.comment }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to the Car Collector</h1>

{% endblock  %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Car</h1>

  <h4>Are you sure you want to delete <span class="red-text">{{ object.make }} {{object.model}}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn red black-text"> 
    <a href="{% url 'detail' car.id %}" class="red-text">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="red-text">{{object.make}} {{object.model}}</span></h1>
{% else %}
    <h1>Add Car</h1>
{% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" class="btn red black-text">
    </form>

{% endblock %}

main_app/templates/main_app/part_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Part</h1>

  <h4>Are you sure you want to delete <span class="red-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn red black-text"> 
    <a href="{% url 'parts_detail' object.id %}" class="red-text">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/part_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Part Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title red-text">{{ part.name }}</span>
        <p>Type: {{ part.type }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'parts_update' part.id %}" class="red-text">Edit</a>
        <a href="{% url 'parts_delete' part.id %}" class="red-text">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/part_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="red-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Part</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn red black-text">
  </form>
{% endblock %}

main_app/templates/main_app/part_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Part List</h1>

{% for part in part_list %}
  <a href="{% url 'parts_detail' part.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title red-text"><b>{{ part.name }}</b></span>
            <p class="black-text"><b>Type:</b> {{ part.type }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}